### ISSUE TITLE
Zookeeper API calls block indefinately when being called from inside Process watcher method

### ISSUE THREAD

**Issue by Kartikkumar-Shetty** [shayhatsor/zookeeper#42]
I wrote a simple leader election code.
Everything workfine in the intial run and the code connects to zookeeper.
Now when one of the nodes gets disconnected, the other node's Process method gets called, but when I make  any zookeeper api method call(like getchildren() etc) from inside this Process method the function gets stuck on the wait() indefinitely, like if I make a 

Process(){
Task<ChildrenResult> t= this.zk.getChildrenAsync(node,null);
t.Wait();
}
the code waits on t.Wait() and does not proceed, and a few seconds later the ephermal znode for this node gets deleted from zookeeper, but the code still stuck on the t.wait() line.

very rarely, like 1 out of 20 times, the code proceeds without any problem

I am trying this on .NET Core  Version:   3.1.101, Ubuntu 18.04

**Comment by shayhatsor** [comment]
Your code mixes async and sync code.
The ZK client is async and your code calls `Wait()` which blocks the thread till done.
Notice the signature of the method:
```csharp
public abstract Task process(WatchedEvent @event);
```
Therefore your code should look something like:
```csharp
public Task process(WatchedEvent @event)
{
   return this.zk.getChildrenAsync(node,null);
}
```
In your case, I suspect won't work either. Since you can't call `getChildrenAsync` from within the process method. It'll cause a deadlock since `getChildrenAsync` itself creates an `@event`.
The solution is to use the `process` method to notify another thread/task about the event.
A complete working example: https://github.com/shayhatsor/zookeeper/tree/trunk/src/recipes/election

**Comment by Kartikkumar-Shetty** [comment]
In the getChildrenAsync  method, I am passing null as the 2nd parameter so it will not fire the watch event.
However calling the getChildrenAsync method in a different thread from inside the Process method works. Thanks. I will close this issue.
