### ISSUE TITLE
Endless ZooKeeper reconnection for sessionTimeout parameter below 1000

### ISSUE THREAD

**Issue by nj4x** [shayhatsor/zookeeper#5]
Please use this gist to reproduce - https://gist.github.com/nj4x/b496d492b6b31c7279dc

**Comment by nj4x** [comment]
It also does not connect to already running ZooKeeper server:

```
            private static void Main(string[] args)
            {
    //            while(!IsPortAvailable()) { 
    //                Console.WriteLine("Please ensure ZooKeeper is not running at localhost:2181");
    //                Task.Delay(5000).Wait();
    //            }
                Test().Wait();
            }
```

**Comment by shayhatsor** [comment]
What happens here is the following:
1) you give the client a low ping response timeout
2) the client throws session expired because the server didn't react in time
3) the client assumes the server was down and attempts reconnect.
this is the design of the java client.
keep in mind that the zookeeper server's default is 4000.
I've been using 2000 in some scenarios, it doesn't affect the server's default minimum.
this value is passed to the server, which can decide it's too low for it. on the client side, AFAIK there's no minimum so you can shoot yourself in the foot.
P.S. on my end, testing your code sample could even go down to 100. to repro your issue I gave it 10 so I'll be able to confirm my suspicion.

**Comment by shayhatsor** [comment]
also, beware of debugging... when you're dealing with such low timeouts you basically can't debug without getting session expired exceptions. I usually put a 10000 when i debug. In production, 4000 is a good choice.

**Comment by nj4x** [comment]
got it, thank you very much!
